version: v1

labels:
  - label: 'setting'
    matcher:
      title: '\bsetting\b'
      branch: '^setting\/'

  - label: 'feat'
    matcher:
      title: '\bfeat\b|\bfeature\b'
      branch: '^feat\/|^feature\/'

  - label: 'fix'
    matcher:
      title: '\bfix\b'
      branch: '^fix\/'

  - label: 'api'
    matcher:
      title: '\bapi\b'
      branch: '^api\/'

  - label: 'refactor'
    matcher:
      title: '\brefactor\b'
      branch: '^refactor\/'

  - label: 'chore'
    matcher:
      title: '\bchore\b'
      branch: '^chore\/'

  - label: 'deploy'
    matcher:
      title: '\bdeploy\b'
      branch: '^deploy\/'

  - label: 'comment'
    matcher:
      title: '\bcomment\b'
      branch: '^comment\/'

  - label: 'test'
    matcher:
      title: '\btest\b'
      branch: '^test\/'

  - label: 'docs'
    matcher:
      title: '\bdocs\b|\breadme\b'
      branch: '^docs\/'

  - label: 'remove'
    matcher:
      title: '\bremove\b'
      branch: '^remove\/'

  - label: 'rename'
    matcher:
      title: '\brename\b'
      branch: '^rename\/'

  - label: 'BREAKING CHANGE'
    matcher:
      title: '\bBREAKING CHANGE\b|\bBREAKING_CHANGE\b'
      branch: '^breaking\/'

  - label: 'HOTFIX'
    matcher:
      title: '\bHOTFIX\b|\bhotfix\b'
      branch: '^hotfix\/'

  - label: 'style'
    matcher:
      title: '\bstyle\b'
      branch: '^style\/'

  - label: 'update'
    matcher:
      title: '\bupdate\b'
      branch: '^update\/'
