REFERENCE_WIDTH = 880

REF_MARGIN = 130
REF_MARGIN_TOP = 40
REF_MARGIN_BOTTOM = 0
REF_PAGE_GAP = 16
REF_LIST_GAP = 12
REF_SELECT_ALL_GAP = 8

ACTION_BUTTON_HEIGHT_SCALE = 0.55
ACTION_BUTTON_WIDTH_SCALE = 0.8
ACTION_BUTTON_TEXT_SIZE = 11
