from PySide6.QtGui import QColor

# 배경
BG_COLOR = QColor("#3A4A63")               
GLOW_COLOR = QColor(255, 255, 255, 128)  

# 사이즈 & 비율
BASE_CANVAS_SIZE = 500
DEFAULT_BUTTON_SIZE = 98
BUTTON_RATIO = DEFAULT_BUTTON_SIZE / BASE_CANVAS_SIZE  
ICON_RATIO = 0.55

# 반응형
MIN_RESPONSIVE_CANVAS = 250

# 글로우 타입
GLOW_INNER_STOP = 0.55             
GLOW_OUTER_STOP = 1.0 

# 애니메이션
PRESS_SCALE = 0.92
PRESS_ANIM_DURATION_MS = 180
