POWER_BUTTON_GAP_REM = 20 / 16
CLICK_GAP_REM = 8 / 16
SUB_GAP_REM = 8 / 16
BUTTON_TOP_GAP_REM = 16 / 16
_BUTTON_BASE_WIDTH_REM = 9.25
_BUTTON_BASE_HEIGHT_REM = 2.875
BUTTON_SCALE = 0.7
BUTTON_WIDTH_REM = _BUTTON_BASE_WIDTH_REM * BUTTON_SCALE
BUTTON_HEIGHT_REM = _BUTTON_BASE_HEIGHT_REM * BUTTON_SCALE

BUTTON_GLOW_BLUR_RADIUS = 6
BUTTON_GLOW_MAX_ALPHA = 130
